package com.knight.Dao;

import com.knight.Bean.authority;

public interface authorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 12:48:10 CST 2019
     */
    int insert(authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 12:48:10 CST 2019
     */
    int insertSelective(authority record);
}