package com.knight.Dao;

import com.knight.Bean.Collations;
import com.knight.Bean.CollationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATIONS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(CollationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATIONS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(CollationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATIONS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(Collations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATIONS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(Collations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATIONS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Collations> selectByExample(CollationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATIONS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Collations record, @Param("example") CollationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATIONS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") Collations record, @Param("example") CollationsExample example);
}