package com.knight.Dao;

import com.knight.Bean.CollationCharacterSetApplicability;
import com.knight.Bean.CollationCharacterSetApplicabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollationCharacterSetApplicabilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATION_CHARACTER_SET_APPLICABILITY
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(CollationCharacterSetApplicabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATION_CHARACTER_SET_APPLICABILITY
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(CollationCharacterSetApplicabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATION_CHARACTER_SET_APPLICABILITY
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(CollationCharacterSetApplicability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATION_CHARACTER_SET_APPLICABILITY
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(CollationCharacterSetApplicability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATION_CHARACTER_SET_APPLICABILITY
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<CollationCharacterSetApplicability> selectByExample(CollationCharacterSetApplicabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATION_CHARACTER_SET_APPLICABILITY
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") CollationCharacterSetApplicability record, @Param("example") CollationCharacterSetApplicabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLLATION_CHARACTER_SET_APPLICABILITY
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") CollationCharacterSetApplicability record, @Param("example") CollationCharacterSetApplicabilityExample example);
}