package com.knight.Dao;

import com.knight.Bean.ColumnsPriv;
import com.knight.Bean.ColumnsPrivExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ColumnsPrivMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(ColumnsPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(ColumnsPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(ColumnsPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(ColumnsPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<ColumnsPriv> selectByExample(ColumnsPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") ColumnsPriv record, @Param("example") ColumnsPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") ColumnsPriv record, @Param("example") ColumnsPrivExample example);
}