package com.knight.Dao;

import com.knight.Bean.Columns;
import com.knight.Bean.ColumnsExample;
import com.knight.Bean.ColumnsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ColumnsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(ColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(ColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(ColumnsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(ColumnsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<ColumnsWithBLOBs> selectByExampleWithBLOBs(ColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Columns> selectByExample(ColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") ColumnsWithBLOBs record, @Param("example") ColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") ColumnsWithBLOBs record, @Param("example") ColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COLUMNS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") Columns record, @Param("example") ColumnsExample example);
}