package com.knight.Dao;

import com.knight.Bean.comment;

public interface commentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sat Dec 28 12:48:10 CST 2019
     */
    int insert(comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sat Dec 28 12:48:10 CST 2019
     */
    int insertSelective(comment record);
}