package com.knight.Dao;

import com.knight.Bean.CondInstances;
import com.knight.Bean.CondInstancesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CondInstancesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cond_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(CondInstancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cond_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(CondInstancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cond_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(CondInstances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cond_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(CondInstances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cond_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<CondInstances> selectByExample(CondInstancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cond_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") CondInstances record, @Param("example") CondInstancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cond_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") CondInstances record, @Param("example") CondInstancesExample example);
}