package com.knight.Dao;

import com.knight.Bean.Db;
import com.knight.Bean.DbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(DbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(DbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(Db record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(Db record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Db> selectByExample(DbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Db record, @Param("example") DbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") Db record, @Param("example") DbExample example);
}