package com.knight.Dao;

import com.knight.Bean.EngineCost;
import com.knight.Bean.EngineCostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EngineCostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engine_cost
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(EngineCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engine_cost
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(EngineCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engine_cost
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(EngineCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engine_cost
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(EngineCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engine_cost
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<EngineCost> selectByExample(EngineCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engine_cost
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") EngineCost record, @Param("example") EngineCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engine_cost
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") EngineCost record, @Param("example") EngineCostExample example);
}