package com.knight.Dao;

import com.knight.Bean.EventsStatementsCurrent;
import com.knight.Bean.EventsStatementsCurrentExample;
import com.knight.Bean.EventsStatementsCurrentWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventsStatementsCurrentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(EventsStatementsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(EventsStatementsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(EventsStatementsCurrentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(EventsStatementsCurrentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<EventsStatementsCurrentWithBLOBs> selectByExampleWithBLOBs(EventsStatementsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<EventsStatementsCurrent> selectByExample(EventsStatementsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") EventsStatementsCurrentWithBLOBs record, @Param("example") EventsStatementsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") EventsStatementsCurrentWithBLOBs record, @Param("example") EventsStatementsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") EventsStatementsCurrent record, @Param("example") EventsStatementsCurrentExample example);
}