package com.knight.Dao;

import com.knight.Bean.EventsStagesCurrent;
import com.knight.Bean.EventsStagesCurrentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventsStagesCurrentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_stages_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(EventsStagesCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_stages_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(EventsStagesCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_stages_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(EventsStagesCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_stages_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(EventsStagesCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_stages_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<EventsStagesCurrent> selectByExample(EventsStagesCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_stages_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") EventsStagesCurrent record, @Param("example") EventsStagesCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_stages_current
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") EventsStagesCurrent record, @Param("example") EventsStagesCurrentExample example);
}