package com.knight.Dao;

import com.knight.Bean.EventsStatementsHistory;
import com.knight.Bean.EventsStatementsHistoryExample;
import com.knight.Bean.EventsStatementsHistoryWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventsStatementsHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(EventsStatementsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(EventsStatementsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(EventsStatementsHistoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(EventsStatementsHistoryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<EventsStatementsHistoryWithBLOBs> selectByExampleWithBLOBs(EventsStatementsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<EventsStatementsHistory> selectByExample(EventsStatementsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") EventsStatementsHistoryWithBLOBs record, @Param("example") EventsStatementsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") EventsStatementsHistoryWithBLOBs record, @Param("example") EventsStatementsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") EventsStatementsHistory record, @Param("example") EventsStatementsHistoryExample example);
}