package com.knight.Dao;

import com.knight.Bean.EventsWaitsHistory;
import com.knight.Bean.EventsWaitsHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventsWaitsHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(EventsWaitsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(EventsWaitsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(EventsWaitsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(EventsWaitsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<EventsWaitsHistory> selectByExample(EventsWaitsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") EventsWaitsHistory record, @Param("example") EventsWaitsHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_waits_history
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") EventsWaitsHistory record, @Param("example") EventsWaitsHistoryExample example);
}