package com.knight.Dao;

import com.knight.Bean.fans;

public interface fansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans
     *
     * @mbg.generated Sat Dec 28 12:48:10 CST 2019
     */
    int insert(fans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans
     *
     * @mbg.generated Sat Dec 28 12:48:10 CST 2019
     */
    int insertSelective(fans record);
}