package com.knight.Dao;

import com.knight.Bean.FileSummaryByEventName;
import com.knight.Bean.FileSummaryByEventNameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileSummaryByEventNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_summary_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(FileSummaryByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_summary_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(FileSummaryByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_summary_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(FileSummaryByEventName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_summary_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(FileSummaryByEventName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_summary_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<FileSummaryByEventName> selectByExample(FileSummaryByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_summary_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") FileSummaryByEventName record, @Param("example") FileSummaryByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_summary_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") FileSummaryByEventName record, @Param("example") FileSummaryByEventNameExample example);
}