package com.knight.Dao;

import com.knight.Bean.Files;
import com.knight.Bean.FilesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Files> selectByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Files record, @Param("example") FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") Files record, @Param("example") FilesExample example);
}