package com.knight.Dao;

import com.knight.Bean.FileInstances;
import com.knight.Bean.FileInstancesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileInstancesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(FileInstancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(FileInstancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(FileInstances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(FileInstances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<FileInstances> selectByExample(FileInstancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") FileInstances record, @Param("example") FileInstancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") FileInstances record, @Param("example") FileInstancesExample example);
}