package com.knight.Dao;

import com.knight.Bean.FollowTrackV;
import com.knight.Bean.FollowTrackVExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FollowTrackVMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_track_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(FollowTrackVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_track_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(FollowTrackVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_track_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(FollowTrackV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_track_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(FollowTrackV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_track_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<FollowTrackV> selectByExampleWithBLOBs(FollowTrackVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_track_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<FollowTrackV> selectByExample(FollowTrackVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_track_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") FollowTrackV record, @Param("example") FollowTrackVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_track_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") FollowTrackV record, @Param("example") FollowTrackVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow_track_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") FollowTrackV record, @Param("example") FollowTrackVExample example);
}