package com.knight.Dao;

import com.knight.Bean.Func;
import com.knight.Bean.FuncExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FuncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(FuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(FuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(Func record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(Func record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<Func> selectByExample(FuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") Func record, @Param("example") FuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") Func record, @Param("example") FuncExample example);
}