package com.knight.Dao;

import com.knight.Bean.GlobalVariables;
import com.knight.Bean.GlobalVariablesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GlobalVariablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_variables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(GlobalVariablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_variables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(GlobalVariablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_variables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(GlobalVariables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_variables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(GlobalVariables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_variables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<GlobalVariables> selectByExample(GlobalVariablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_variables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") GlobalVariables record, @Param("example") GlobalVariablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_variables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") GlobalVariables record, @Param("example") GlobalVariablesExample example);
}