package com.knight.Dao;

import com.knight.Bean.GlobalStatus;
import com.knight.Bean.GlobalStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GlobalStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_status
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(GlobalStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_status
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(GlobalStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_status
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(GlobalStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_status
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(GlobalStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_status
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<GlobalStatus> selectByExample(GlobalStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_status
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") GlobalStatus record, @Param("example") GlobalStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_status
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") GlobalStatus record, @Param("example") GlobalStatusExample example);
}