package com.knight.Dao;

import com.knight.Bean.HelpTopic;
import com.knight.Bean.HelpTopicExample;
import com.knight.Bean.HelpTopicWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HelpTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_topic
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(HelpTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_topic
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(HelpTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_topic
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(HelpTopicWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_topic
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(HelpTopicWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_topic
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<HelpTopicWithBLOBs> selectByExampleWithBLOBs(HelpTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_topic
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<HelpTopic> selectByExample(HelpTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_topic
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") HelpTopicWithBLOBs record, @Param("example") HelpTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_topic
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") HelpTopicWithBLOBs record, @Param("example") HelpTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_topic
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") HelpTopic record, @Param("example") HelpTopicExample example);
}