package com.knight.Dao;

import com.knight.Bean.HelpCategory;
import com.knight.Bean.HelpCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HelpCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_category
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(HelpCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_category
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(HelpCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_category
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(HelpCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_category
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(HelpCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_category
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<HelpCategory> selectByExampleWithBLOBs(HelpCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_category
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<HelpCategory> selectByExample(HelpCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_category
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") HelpCategory record, @Param("example") HelpCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_category
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") HelpCategory record, @Param("example") HelpCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_category
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") HelpCategory record, @Param("example") HelpCategoryExample example);
}