package com.knight.Dao;

import com.knight.Bean.HelpRelation;
import com.knight.Bean.HelpRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HelpRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_relation
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(HelpRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_relation
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(HelpRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_relation
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(HelpRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_relation
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(HelpRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_relation
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<HelpRelation> selectByExample(HelpRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_relation
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") HelpRelation record, @Param("example") HelpRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_relation
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") HelpRelation record, @Param("example") HelpRelationExample example);
}