package com.knight.Dao;

import com.knight.Bean.HostSummaryByStatementType;
import com.knight.Bean.HostSummaryByStatementTypeExample;
import com.knight.Bean.HostSummaryByStatementTypeWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HostSummaryByStatementTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(HostSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(HostSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(HostSummaryByStatementTypeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(HostSummaryByStatementTypeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<HostSummaryByStatementTypeWithBLOBs> selectByExampleWithBLOBs(HostSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<HostSummaryByStatementType> selectByExample(HostSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") HostSummaryByStatementTypeWithBLOBs record, @Param("example") HostSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") HostSummaryByStatementTypeWithBLOBs record, @Param("example") HostSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") HostSummaryByStatementType record, @Param("example") HostSummaryByStatementTypeExample example);
}