package com.knight.Dao;

import com.knight.Bean.HostSummaryByStatementLatency;
import com.knight.Bean.HostSummaryByStatementLatencyExample;
import com.knight.Bean.HostSummaryByStatementLatencyWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HostSummaryByStatementLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(HostSummaryByStatementLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(HostSummaryByStatementLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(HostSummaryByStatementLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(HostSummaryByStatementLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<HostSummaryByStatementLatencyWithBLOBs> selectByExampleWithBLOBs(HostSummaryByStatementLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<HostSummaryByStatementLatency> selectByExample(HostSummaryByStatementLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") HostSummaryByStatementLatencyWithBLOBs record, @Param("example") HostSummaryByStatementLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") HostSummaryByStatementLatencyWithBLOBs record, @Param("example") HostSummaryByStatementLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") HostSummaryByStatementLatency record, @Param("example") HostSummaryByStatementLatencyExample example);
}