package com.knight.Dao;

import com.knight.Bean.HostSummaryByStages;
import com.knight.Bean.HostSummaryByStagesExample;
import com.knight.Bean.HostSummaryByStagesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HostSummaryByStagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(HostSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(HostSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(HostSummaryByStagesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(HostSummaryByStagesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<HostSummaryByStagesWithBLOBs> selectByExampleWithBLOBs(HostSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<HostSummaryByStages> selectByExample(HostSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") HostSummaryByStagesWithBLOBs record, @Param("example") HostSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") HostSummaryByStagesWithBLOBs record, @Param("example") HostSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") HostSummaryByStages record, @Param("example") HostSummaryByStagesExample example);
}