package com.knight.Dao;

import com.knight.Bean.HostSummaryByFileIo;
import com.knight.Bean.HostSummaryByFileIoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HostSummaryByFileIoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(HostSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(HostSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(HostSummaryByFileIo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(HostSummaryByFileIo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<HostSummaryByFileIo> selectByExampleWithBLOBs(HostSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<HostSummaryByFileIo> selectByExample(HostSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") HostSummaryByFileIo record, @Param("example") HostSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") HostSummaryByFileIo record, @Param("example") HostSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") HostSummaryByFileIo record, @Param("example") HostSummaryByFileIoExample example);
}