package com.knight.Dao;

import com.knight.Bean.Hosts;
import com.knight.Bean.HostsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HostsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosts
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(HostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosts
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(HostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosts
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(Hosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosts
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(Hosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosts
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<Hosts> selectByExample(HostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosts
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") Hosts record, @Param("example") HostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosts
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") Hosts record, @Param("example") HostsExample example);
}