package com.knight.Dao;

import com.knight.Bean.InnodbBufferPoolStats;
import com.knight.Bean.InnodbBufferPoolStatsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnodbBufferPoolStatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_BUFFER_POOL_STATS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(InnodbBufferPoolStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_BUFFER_POOL_STATS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(InnodbBufferPoolStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_BUFFER_POOL_STATS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(InnodbBufferPoolStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_BUFFER_POOL_STATS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(InnodbBufferPoolStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_BUFFER_POOL_STATS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<InnodbBufferPoolStats> selectByExample(InnodbBufferPoolStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_BUFFER_POOL_STATS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") InnodbBufferPoolStats record, @Param("example") InnodbBufferPoolStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_BUFFER_POOL_STATS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") InnodbBufferPoolStats record, @Param("example") InnodbBufferPoolStatsExample example);
}