package com.knight.Dao;

import com.knight.Bean.InnodbCmp;
import com.knight.Bean.InnodbCmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnodbCmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(InnodbCmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(InnodbCmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(InnodbCmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(InnodbCmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<InnodbCmp> selectByExample(InnodbCmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") InnodbCmp record, @Param("example") InnodbCmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") InnodbCmp record, @Param("example") InnodbCmpExample example);
}