package com.knight.Dao;

import com.knight.Bean.InnodbFtDefaultStopword;
import com.knight.Bean.InnodbFtDefaultStopwordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnodbFtDefaultStopwordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_DEFAULT_STOPWORD
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(InnodbFtDefaultStopwordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_DEFAULT_STOPWORD
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(InnodbFtDefaultStopwordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_DEFAULT_STOPWORD
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(InnodbFtDefaultStopword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_DEFAULT_STOPWORD
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(InnodbFtDefaultStopword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_DEFAULT_STOPWORD
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<InnodbFtDefaultStopword> selectByExample(InnodbFtDefaultStopwordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_DEFAULT_STOPWORD
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") InnodbFtDefaultStopword record, @Param("example") InnodbFtDefaultStopwordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_DEFAULT_STOPWORD
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") InnodbFtDefaultStopword record, @Param("example") InnodbFtDefaultStopwordExample example);
}