package com.knight.Dao;

import com.knight.Bean.InnodbCmpmemReset;
import com.knight.Bean.InnodbCmpmemResetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnodbCmpmemResetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMPMEM_RESET
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(InnodbCmpmemResetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMPMEM_RESET
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(InnodbCmpmemResetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMPMEM_RESET
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(InnodbCmpmemReset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMPMEM_RESET
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(InnodbCmpmemReset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMPMEM_RESET
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<InnodbCmpmemReset> selectByExample(InnodbCmpmemResetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMPMEM_RESET
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") InnodbCmpmemReset record, @Param("example") InnodbCmpmemResetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMPMEM_RESET
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") InnodbCmpmemReset record, @Param("example") InnodbCmpmemResetExample example);
}