package com.knight.Dao;

import com.knight.Bean.InnodbLockWaits;
import com.knight.Bean.InnodbLockWaitsExample;
import com.knight.Bean.InnodbLockWaitsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnodbLockWaitsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(InnodbLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(InnodbLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(InnodbLockWaitsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(InnodbLockWaitsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<InnodbLockWaitsWithBLOBs> selectByExampleWithBLOBs(InnodbLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<InnodbLockWaits> selectByExample(InnodbLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") InnodbLockWaitsWithBLOBs record, @Param("example") InnodbLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") InnodbLockWaitsWithBLOBs record, @Param("example") InnodbLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") InnodbLockWaits record, @Param("example") InnodbLockWaitsExample example);
}