package com.knight.Dao;

import com.knight.Bean.InnodbTempTableInfo;
import com.knight.Bean.InnodbTempTableInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnodbTempTableInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_TEMP_TABLE_INFO
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(InnodbTempTableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_TEMP_TABLE_INFO
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(InnodbTempTableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_TEMP_TABLE_INFO
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(InnodbTempTableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_TEMP_TABLE_INFO
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(InnodbTempTableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_TEMP_TABLE_INFO
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<InnodbTempTableInfo> selectByExample(InnodbTempTableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_TEMP_TABLE_INFO
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") InnodbTempTableInfo record, @Param("example") InnodbTempTableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_TEMP_TABLE_INFO
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") InnodbTempTableInfo record, @Param("example") InnodbTempTableInfoExample example);
}