package com.knight.Dao;

import com.knight.Bean.InnodbCmpPerIndexReset;
import com.knight.Bean.InnodbCmpPerIndexResetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnodbCmpPerIndexResetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP_PER_INDEX_RESET
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(InnodbCmpPerIndexResetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP_PER_INDEX_RESET
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(InnodbCmpPerIndexResetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP_PER_INDEX_RESET
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(InnodbCmpPerIndexReset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP_PER_INDEX_RESET
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(InnodbCmpPerIndexReset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP_PER_INDEX_RESET
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<InnodbCmpPerIndexReset> selectByExample(InnodbCmpPerIndexResetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP_PER_INDEX_RESET
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") InnodbCmpPerIndexReset record, @Param("example") InnodbCmpPerIndexResetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_CMP_PER_INDEX_RESET
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") InnodbCmpPerIndexReset record, @Param("example") InnodbCmpPerIndexResetExample example);
}