package com.knight.Dao;

import com.knight.Bean.InnodbLocks;
import com.knight.Bean.InnodbLocksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnodbLocksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_LOCKS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(InnodbLocksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_LOCKS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(InnodbLocksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_LOCKS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(InnodbLocks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_LOCKS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(InnodbLocks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_LOCKS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<InnodbLocks> selectByExample(InnodbLocksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_LOCKS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") InnodbLocks record, @Param("example") InnodbLocksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_LOCKS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") InnodbLocks record, @Param("example") InnodbLocksExample example);
}