package com.knight.Dao;

import com.knight.Bean.InnodbBufferStatsBySchema;
import com.knight.Bean.InnodbBufferStatsBySchemaExample;
import com.knight.Bean.InnodbBufferStatsBySchemaWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnodbBufferStatsBySchemaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(InnodbBufferStatsBySchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(InnodbBufferStatsBySchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(InnodbBufferStatsBySchemaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(InnodbBufferStatsBySchemaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<InnodbBufferStatsBySchemaWithBLOBs> selectByExampleWithBLOBs(InnodbBufferStatsBySchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<InnodbBufferStatsBySchema> selectByExample(InnodbBufferStatsBySchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") InnodbBufferStatsBySchemaWithBLOBs record, @Param("example") InnodbBufferStatsBySchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") InnodbBufferStatsBySchemaWithBLOBs record, @Param("example") InnodbBufferStatsBySchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") InnodbBufferStatsBySchema record, @Param("example") InnodbBufferStatsBySchemaExample example);
}