package com.knight.Dao;

import com.knight.Bean.InnodbSysForeignCols;
import com.knight.Bean.InnodbSysForeignColsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnodbSysForeignColsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_FOREIGN_COLS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(InnodbSysForeignColsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_FOREIGN_COLS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(InnodbSysForeignColsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_FOREIGN_COLS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(InnodbSysForeignCols record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_FOREIGN_COLS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(InnodbSysForeignCols record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_FOREIGN_COLS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<InnodbSysForeignCols> selectByExample(InnodbSysForeignColsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_FOREIGN_COLS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") InnodbSysForeignCols record, @Param("example") InnodbSysForeignColsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_FOREIGN_COLS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") InnodbSysForeignCols record, @Param("example") InnodbSysForeignColsExample example);
}