package com.knight.Dao;

import com.knight.Bean.InnodbSysTables;
import com.knight.Bean.InnodbSysTablesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnodbSysTablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_TABLES
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(InnodbSysTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_TABLES
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(InnodbSysTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_TABLES
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(InnodbSysTables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_TABLES
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(InnodbSysTables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_TABLES
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<InnodbSysTables> selectByExample(InnodbSysTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_TABLES
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") InnodbSysTables record, @Param("example") InnodbSysTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_SYS_TABLES
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") InnodbSysTables record, @Param("example") InnodbSysTablesExample example);
}