package com.knight.Dao;

import com.knight.Bean.InnodbBufferStatsByTable;
import com.knight.Bean.InnodbBufferStatsByTableExample;
import com.knight.Bean.InnodbBufferStatsByTableWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InnodbBufferStatsByTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(InnodbBufferStatsByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(InnodbBufferStatsByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(InnodbBufferStatsByTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(InnodbBufferStatsByTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<InnodbBufferStatsByTableWithBLOBs> selectByExampleWithBLOBs(InnodbBufferStatsByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<InnodbBufferStatsByTable> selectByExample(InnodbBufferStatsByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") InnodbBufferStatsByTableWithBLOBs record, @Param("example") InnodbBufferStatsByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") InnodbBufferStatsByTableWithBLOBs record, @Param("example") InnodbBufferStatsByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") InnodbBufferStatsByTable record, @Param("example") InnodbBufferStatsByTableExample example);
}