package com.knight.Dao;

import com.knight.Bean.IoByThreadByLatency;
import com.knight.Bean.IoByThreadByLatencyExample;
import com.knight.Bean.IoByThreadByLatencyWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IoByThreadByLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_by_thread_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(IoByThreadByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_by_thread_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(IoByThreadByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_by_thread_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(IoByThreadByLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_by_thread_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(IoByThreadByLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_by_thread_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<IoByThreadByLatencyWithBLOBs> selectByExampleWithBLOBs(IoByThreadByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_by_thread_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<IoByThreadByLatency> selectByExample(IoByThreadByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_by_thread_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") IoByThreadByLatencyWithBLOBs record, @Param("example") IoByThreadByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_by_thread_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") IoByThreadByLatencyWithBLOBs record, @Param("example") IoByThreadByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_by_thread_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") IoByThreadByLatency record, @Param("example") IoByThreadByLatencyExample example);
}