package com.knight.Dao;

import com.knight.Bean.IoGlobalByWaitByLatency;
import com.knight.Bean.IoGlobalByWaitByLatencyExample;
import com.knight.Bean.IoGlobalByWaitByLatencyWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IoGlobalByWaitByLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(IoGlobalByWaitByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(IoGlobalByWaitByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(IoGlobalByWaitByLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(IoGlobalByWaitByLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<IoGlobalByWaitByLatencyWithBLOBs> selectByExampleWithBLOBs(IoGlobalByWaitByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<IoGlobalByWaitByLatency> selectByExample(IoGlobalByWaitByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") IoGlobalByWaitByLatencyWithBLOBs record, @Param("example") IoGlobalByWaitByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") IoGlobalByWaitByLatencyWithBLOBs record, @Param("example") IoGlobalByWaitByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") IoGlobalByWaitByLatency record, @Param("example") IoGlobalByWaitByLatencyExample example);
}