package com.knight.Dao;

import com.knight.Bean.IoGlobalByWaitByBytes;
import com.knight.Bean.IoGlobalByWaitByBytesExample;
import com.knight.Bean.IoGlobalByWaitByBytesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IoGlobalByWaitByBytesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(IoGlobalByWaitByBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(IoGlobalByWaitByBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(IoGlobalByWaitByBytesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(IoGlobalByWaitByBytesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<IoGlobalByWaitByBytesWithBLOBs> selectByExampleWithBLOBs(IoGlobalByWaitByBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<IoGlobalByWaitByBytes> selectByExample(IoGlobalByWaitByBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") IoGlobalByWaitByBytesWithBLOBs record, @Param("example") IoGlobalByWaitByBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") IoGlobalByWaitByBytesWithBLOBs record, @Param("example") IoGlobalByWaitByBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_wait_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") IoGlobalByWaitByBytes record, @Param("example") IoGlobalByWaitByBytesExample example);
}