package com.knight.Dao;

import com.knight.Bean.IoGlobalByFileByLatency;
import com.knight.Bean.IoGlobalByFileByLatencyExample;
import com.knight.Bean.IoGlobalByFileByLatencyWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IoGlobalByFileByLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(IoGlobalByFileByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(IoGlobalByFileByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(IoGlobalByFileByLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(IoGlobalByFileByLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<IoGlobalByFileByLatencyWithBLOBs> selectByExampleWithBLOBs(IoGlobalByFileByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<IoGlobalByFileByLatency> selectByExample(IoGlobalByFileByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") IoGlobalByFileByLatencyWithBLOBs record, @Param("example") IoGlobalByFileByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") IoGlobalByFileByLatencyWithBLOBs record, @Param("example") IoGlobalByFileByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") IoGlobalByFileByLatency record, @Param("example") IoGlobalByFileByLatencyExample example);
}