package com.knight.Dao;

import com.knight.Bean.KeyColumnUsage;
import com.knight.Bean.KeyColumnUsageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KeyColumnUsageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEY_COLUMN_USAGE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(KeyColumnUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEY_COLUMN_USAGE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(KeyColumnUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEY_COLUMN_USAGE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(KeyColumnUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEY_COLUMN_USAGE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(KeyColumnUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEY_COLUMN_USAGE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<KeyColumnUsage> selectByExample(KeyColumnUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEY_COLUMN_USAGE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") KeyColumnUsage record, @Param("example") KeyColumnUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEY_COLUMN_USAGE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") KeyColumnUsage record, @Param("example") KeyColumnUsageExample example);
}