package com.knight.Dao;

import com.knight.Bean.MemoryByThreadByCurrentBytes;
import com.knight.Bean.MemoryByThreadByCurrentBytesExample;
import com.knight.Bean.MemoryByThreadByCurrentBytesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemoryByThreadByCurrentBytesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_thread_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(MemoryByThreadByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_thread_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(MemoryByThreadByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_thread_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(MemoryByThreadByCurrentBytesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_thread_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(MemoryByThreadByCurrentBytesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_thread_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<MemoryByThreadByCurrentBytesWithBLOBs> selectByExampleWithBLOBs(MemoryByThreadByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_thread_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<MemoryByThreadByCurrentBytes> selectByExample(MemoryByThreadByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_thread_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") MemoryByThreadByCurrentBytesWithBLOBs record, @Param("example") MemoryByThreadByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_thread_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") MemoryByThreadByCurrentBytesWithBLOBs record, @Param("example") MemoryByThreadByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_thread_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") MemoryByThreadByCurrentBytes record, @Param("example") MemoryByThreadByCurrentBytesExample example);
}