package com.knight.Dao;

import com.knight.Bean.MemoryByHostByCurrentBytes;
import com.knight.Bean.MemoryByHostByCurrentBytesExample;
import com.knight.Bean.MemoryByHostByCurrentBytesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemoryByHostByCurrentBytesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(MemoryByHostByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(MemoryByHostByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(MemoryByHostByCurrentBytesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(MemoryByHostByCurrentBytesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<MemoryByHostByCurrentBytesWithBLOBs> selectByExampleWithBLOBs(MemoryByHostByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<MemoryByHostByCurrentBytes> selectByExample(MemoryByHostByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") MemoryByHostByCurrentBytesWithBLOBs record, @Param("example") MemoryByHostByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") MemoryByHostByCurrentBytesWithBLOBs record, @Param("example") MemoryByHostByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") MemoryByHostByCurrentBytes record, @Param("example") MemoryByHostByCurrentBytesExample example);
}