package com.knight.Dao;

import com.knight.Bean.MemorySummaryByHostByEventName;
import com.knight.Bean.MemorySummaryByHostByEventNameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemorySummaryByHostByEventNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_host_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(MemorySummaryByHostByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_host_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(MemorySummaryByHostByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_host_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(MemorySummaryByHostByEventName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_host_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(MemorySummaryByHostByEventName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_host_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<MemorySummaryByHostByEventName> selectByExample(MemorySummaryByHostByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_host_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") MemorySummaryByHostByEventName record, @Param("example") MemorySummaryByHostByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_host_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") MemorySummaryByHostByEventName record, @Param("example") MemorySummaryByHostByEventNameExample example);
}