package com.knight.Dao;

import com.knight.Bean.MemorySummaryByAccountByEventName;
import com.knight.Bean.MemorySummaryByAccountByEventNameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemorySummaryByAccountByEventNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_account_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(MemorySummaryByAccountByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_account_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(MemorySummaryByAccountByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_account_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(MemorySummaryByAccountByEventName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_account_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(MemorySummaryByAccountByEventName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_account_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<MemorySummaryByAccountByEventName> selectByExample(MemorySummaryByAccountByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_account_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") MemorySummaryByAccountByEventName record, @Param("example") MemorySummaryByAccountByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_account_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") MemorySummaryByAccountByEventName record, @Param("example") MemorySummaryByAccountByEventNameExample example);
}