package com.knight.Dao;

import com.knight.Bean.MemorySummaryByUserByEventName;
import com.knight.Bean.MemorySummaryByUserByEventNameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemorySummaryByUserByEventNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_user_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(MemorySummaryByUserByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_user_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(MemorySummaryByUserByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_user_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(MemorySummaryByUserByEventName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_user_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(MemorySummaryByUserByEventName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_user_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<MemorySummaryByUserByEventName> selectByExample(MemorySummaryByUserByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_user_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") MemorySummaryByUserByEventName record, @Param("example") MemorySummaryByUserByEventNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memory_summary_by_user_by_event_name
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") MemorySummaryByUserByEventName record, @Param("example") MemorySummaryByUserByEventNameExample example);
}