package com.knight.Dao;

import com.knight.Bean.Metrics;
import com.knight.Bean.MetricsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MetricsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metrics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(MetricsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metrics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(MetricsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metrics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(Metrics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metrics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(Metrics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metrics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Metrics> selectByExampleWithBLOBs(MetricsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metrics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Metrics> selectByExample(MetricsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metrics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Metrics record, @Param("example") MetricsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metrics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Metrics record, @Param("example") MetricsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metrics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") Metrics record, @Param("example") MetricsExample example);
}