package com.knight.Dao;

import com.knight.Bean.MusicBandV;
import com.knight.Bean.MusicBandVExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MusicBandVMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_band_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(MusicBandVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_band_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(MusicBandVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_band_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(MusicBandV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_band_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(MusicBandV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_band_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<MusicBandV> selectByExample(MusicBandVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_band_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") MusicBandV record, @Param("example") MusicBandVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_band_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") MusicBandV record, @Param("example") MusicBandVExample example);
}