package com.knight.Dao;

import com.knight.Bean.MusicCommentInfoV;
import com.knight.Bean.MusicCommentInfoVExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MusicCommentInfoVMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(MusicCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(MusicCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(MusicCommentInfoV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(MusicCommentInfoV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<MusicCommentInfoV> selectByExampleWithBLOBs(MusicCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<MusicCommentInfoV> selectByExample(MusicCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") MusicCommentInfoV record, @Param("example") MusicCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") MusicCommentInfoV record, @Param("example") MusicCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") MusicCommentInfoV record, @Param("example") MusicCommentInfoVExample example);
}