package com.knight.Dao;

import com.knight.Bean.NdbBinlogIndex;
import com.knight.Bean.NdbBinlogIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NdbBinlogIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ndb_binlog_index
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(NdbBinlogIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ndb_binlog_index
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(NdbBinlogIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ndb_binlog_index
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(NdbBinlogIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ndb_binlog_index
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(NdbBinlogIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ndb_binlog_index
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<NdbBinlogIndex> selectByExample(NdbBinlogIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ndb_binlog_index
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") NdbBinlogIndex record, @Param("example") NdbBinlogIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ndb_binlog_index
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") NdbBinlogIndex record, @Param("example") NdbBinlogIndexExample example);
}