package com.knight.Dao;

import com.knight.Bean.OptimizerTrace;
import com.knight.Bean.OptimizerTraceExample;
import com.knight.Bean.OptimizerTraceWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptimizerTraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(OptimizerTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(OptimizerTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(OptimizerTraceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(OptimizerTraceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<OptimizerTraceWithBLOBs> selectByExampleWithBLOBs(OptimizerTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<OptimizerTrace> selectByExample(OptimizerTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") OptimizerTraceWithBLOBs record, @Param("example") OptimizerTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") OptimizerTraceWithBLOBs record, @Param("example") OptimizerTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") OptimizerTrace record, @Param("example") OptimizerTraceExample example);
}