package com.knight.Dao;

import com.knight.Bean.Parameters;
import com.knight.Bean.ParametersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParametersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETERS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(ParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETERS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(ParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETERS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(Parameters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETERS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(Parameters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETERS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Parameters> selectByExampleWithBLOBs(ParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETERS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Parameters> selectByExample(ParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETERS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Parameters record, @Param("example") ParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETERS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Parameters record, @Param("example") ParametersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARAMETERS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") Parameters record, @Param("example") ParametersExample example);
}