package com.knight.Dao;

import com.knight.Bean.PerformanceTimers;
import com.knight.Bean.PerformanceTimersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PerformanceTimersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_timers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(PerformanceTimersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_timers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(PerformanceTimersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_timers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(PerformanceTimers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_timers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(PerformanceTimers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_timers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<PerformanceTimers> selectByExample(PerformanceTimersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_timers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") PerformanceTimers record, @Param("example") PerformanceTimersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance_timers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") PerformanceTimers record, @Param("example") PerformanceTimersExample example);
}