package com.knight.Dao;

import com.knight.Bean.Plugins;
import com.knight.Bean.PluginsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PluginsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLUGINS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(PluginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLUGINS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(PluginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLUGINS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(Plugins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLUGINS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(Plugins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLUGINS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Plugins> selectByExampleWithBLOBs(PluginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLUGINS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Plugins> selectByExample(PluginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLUGINS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Plugins record, @Param("example") PluginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLUGINS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Plugins record, @Param("example") PluginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLUGINS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") Plugins record, @Param("example") PluginsExample example);
}