package com.knight.Dao;

import com.knight.Bean.ProxiesPriv;
import com.knight.Bean.ProxiesPrivExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProxiesPrivMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(ProxiesPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(ProxiesPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(ProxiesPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(ProxiesPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<ProxiesPriv> selectByExample(ProxiesPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProxiesPriv record, @Param("example") ProxiesPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxies_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") ProxiesPriv record, @Param("example") ProxiesPrivExample example);
}