package com.knight.Dao;

import com.knight.Bean.ReferentialConstraints;
import com.knight.Bean.ReferentialConstraintsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReferentialConstraintsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REFERENTIAL_CONSTRAINTS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(ReferentialConstraintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REFERENTIAL_CONSTRAINTS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(ReferentialConstraintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REFERENTIAL_CONSTRAINTS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(ReferentialConstraints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REFERENTIAL_CONSTRAINTS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(ReferentialConstraints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REFERENTIAL_CONSTRAINTS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<ReferentialConstraints> selectByExample(ReferentialConstraintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REFERENTIAL_CONSTRAINTS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") ReferentialConstraints record, @Param("example") ReferentialConstraintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REFERENTIAL_CONSTRAINTS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") ReferentialConstraints record, @Param("example") ReferentialConstraintsExample example);
}