package com.knight.Dao;

import com.knight.Bean.ReplicationApplierStatusByCoordinator;
import com.knight.Bean.ReplicationApplierStatusByCoordinatorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReplicationApplierStatusByCoordinatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_status_by_coordinator
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(ReplicationApplierStatusByCoordinatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_status_by_coordinator
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(ReplicationApplierStatusByCoordinatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_status_by_coordinator
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(ReplicationApplierStatusByCoordinator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_status_by_coordinator
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(ReplicationApplierStatusByCoordinator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_status_by_coordinator
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<ReplicationApplierStatusByCoordinator> selectByExample(ReplicationApplierStatusByCoordinatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_status_by_coordinator
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") ReplicationApplierStatusByCoordinator record, @Param("example") ReplicationApplierStatusByCoordinatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_status_by_coordinator
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") ReplicationApplierStatusByCoordinator record, @Param("example") ReplicationApplierStatusByCoordinatorExample example);
}