package com.knight.Dao;

import com.knight.Bean.ReplicationConnectionConfiguration;
import com.knight.Bean.ReplicationConnectionConfigurationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReplicationConnectionConfigurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_connection_configuration
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(ReplicationConnectionConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_connection_configuration
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(ReplicationConnectionConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_connection_configuration
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(ReplicationConnectionConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_connection_configuration
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(ReplicationConnectionConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_connection_configuration
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<ReplicationConnectionConfiguration> selectByExample(ReplicationConnectionConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_connection_configuration
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") ReplicationConnectionConfiguration record, @Param("example") ReplicationConnectionConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_connection_configuration
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") ReplicationConnectionConfiguration record, @Param("example") ReplicationConnectionConfigurationExample example);
}