package com.knight.Dao;

import com.knight.Bean.ReplicationApplierStatusByWorker;
import com.knight.Bean.ReplicationApplierStatusByWorkerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReplicationApplierStatusByWorkerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_status_by_worker
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(ReplicationApplierStatusByWorkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_status_by_worker
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(ReplicationApplierStatusByWorkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_status_by_worker
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(ReplicationApplierStatusByWorker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_status_by_worker
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(ReplicationApplierStatusByWorker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_status_by_worker
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<ReplicationApplierStatusByWorker> selectByExample(ReplicationApplierStatusByWorkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_status_by_worker
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") ReplicationApplierStatusByWorker record, @Param("example") ReplicationApplierStatusByWorkerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_status_by_worker
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") ReplicationApplierStatusByWorker record, @Param("example") ReplicationApplierStatusByWorkerExample example);
}