package com.knight.Dao;

import com.knight.Bean.ReplicationApplierConfiguration;
import com.knight.Bean.ReplicationApplierConfigurationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReplicationApplierConfigurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_configuration
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(ReplicationApplierConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_configuration
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(ReplicationApplierConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_configuration
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(ReplicationApplierConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_configuration
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(ReplicationApplierConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_configuration
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<ReplicationApplierConfiguration> selectByExample(ReplicationApplierConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_configuration
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") ReplicationApplierConfiguration record, @Param("example") ReplicationApplierConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_applier_configuration
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") ReplicationApplierConfiguration record, @Param("example") ReplicationApplierConfigurationExample example);
}