package com.knight.Dao;

import com.knight.Bean.ReplicationGroupMemberStats;
import com.knight.Bean.ReplicationGroupMemberStatsExample;
import com.knight.Bean.ReplicationGroupMemberStatsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReplicationGroupMemberStatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_group_member_stats
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(ReplicationGroupMemberStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_group_member_stats
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(ReplicationGroupMemberStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_group_member_stats
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(ReplicationGroupMemberStatsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_group_member_stats
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(ReplicationGroupMemberStatsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_group_member_stats
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<ReplicationGroupMemberStatsWithBLOBs> selectByExampleWithBLOBs(ReplicationGroupMemberStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_group_member_stats
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<ReplicationGroupMemberStats> selectByExample(ReplicationGroupMemberStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_group_member_stats
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") ReplicationGroupMemberStatsWithBLOBs record, @Param("example") ReplicationGroupMemberStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_group_member_stats
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") ReplicationGroupMemberStatsWithBLOBs record, @Param("example") ReplicationGroupMemberStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replication_group_member_stats
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") ReplicationGroupMemberStats record, @Param("example") ReplicationGroupMemberStatsExample example);
}