package com.knight.Dao;

import com.knight.Bean.Routines;
import com.knight.Bean.RoutinesExample;
import com.knight.Bean.RoutinesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoutinesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTINES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(RoutinesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTINES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(RoutinesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTINES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(RoutinesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTINES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(RoutinesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTINES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<RoutinesWithBLOBs> selectByExampleWithBLOBs(RoutinesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTINES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Routines> selectByExample(RoutinesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTINES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") RoutinesWithBLOBs record, @Param("example") RoutinesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTINES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") RoutinesWithBLOBs record, @Param("example") RoutinesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUTINES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") Routines record, @Param("example") RoutinesExample example);
}