package com.knight.Dao;

import com.knight.Bean.SchemaTablesWithFullTableScans;
import com.knight.Bean.SchemaTablesWithFullTableScansExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchemaTablesWithFullTableScansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SchemaTablesWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SchemaTablesWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SchemaTablesWithFullTableScans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SchemaTablesWithFullTableScans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SchemaTablesWithFullTableScans> selectByExampleWithBLOBs(SchemaTablesWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SchemaTablesWithFullTableScans> selectByExample(SchemaTablesWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SchemaTablesWithFullTableScans record, @Param("example") SchemaTablesWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SchemaTablesWithFullTableScans record, @Param("example") SchemaTablesWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") SchemaTablesWithFullTableScans record, @Param("example") SchemaTablesWithFullTableScansExample example);
}