package com.knight.Dao;

import com.knight.Bean.SchemaTableLockWaits;
import com.knight.Bean.SchemaTableLockWaitsExample;
import com.knight.Bean.SchemaTableLockWaitsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchemaTableLockWaitsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SchemaTableLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SchemaTableLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SchemaTableLockWaitsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SchemaTableLockWaitsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SchemaTableLockWaitsWithBLOBs> selectByExampleWithBLOBs(SchemaTableLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SchemaTableLockWaits> selectByExample(SchemaTableLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SchemaTableLockWaitsWithBLOBs record, @Param("example") SchemaTableLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SchemaTableLockWaitsWithBLOBs record, @Param("example") SchemaTableLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") SchemaTableLockWaits record, @Param("example") SchemaTableLockWaitsExample example);
}