package com.knight.Dao;

import com.knight.Bean.SchemaTableStatistics;
import com.knight.Bean.SchemaTableStatisticsExample;
import com.knight.Bean.SchemaTableStatisticsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchemaTableStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SchemaTableStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SchemaTableStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SchemaTableStatisticsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SchemaTableStatisticsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SchemaTableStatisticsWithBLOBs> selectByExampleWithBLOBs(SchemaTableStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SchemaTableStatistics> selectByExample(SchemaTableStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SchemaTableStatisticsWithBLOBs record, @Param("example") SchemaTableStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SchemaTableStatisticsWithBLOBs record, @Param("example") SchemaTableStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") SchemaTableStatistics record, @Param("example") SchemaTableStatisticsExample example);
}