package com.knight.Dao;

import com.knight.Bean.SchemaUnusedIndexes;
import com.knight.Bean.SchemaUnusedIndexesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchemaUnusedIndexesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_unused_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(SchemaUnusedIndexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_unused_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(SchemaUnusedIndexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_unused_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(SchemaUnusedIndexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_unused_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(SchemaUnusedIndexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_unused_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<SchemaUnusedIndexes> selectByExample(SchemaUnusedIndexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_unused_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") SchemaUnusedIndexes record, @Param("example") SchemaUnusedIndexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_unused_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") SchemaUnusedIndexes record, @Param("example") SchemaUnusedIndexesExample example);
}