package com.knight.Dao;

import com.knight.Bean.SchemaRedundantIndexes;
import com.knight.Bean.SchemaRedundantIndexesExample;
import com.knight.Bean.SchemaRedundantIndexesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchemaRedundantIndexesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_redundant_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SchemaRedundantIndexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_redundant_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SchemaRedundantIndexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_redundant_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SchemaRedundantIndexesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_redundant_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SchemaRedundantIndexesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_redundant_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SchemaRedundantIndexesWithBLOBs> selectByExampleWithBLOBs(SchemaRedundantIndexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_redundant_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SchemaRedundantIndexes> selectByExample(SchemaRedundantIndexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_redundant_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SchemaRedundantIndexesWithBLOBs record, @Param("example") SchemaRedundantIndexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_redundant_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SchemaRedundantIndexesWithBLOBs record, @Param("example") SchemaRedundantIndexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_redundant_indexes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") SchemaRedundantIndexes record, @Param("example") SchemaRedundantIndexesExample example);
}