package com.knight.Dao;

import com.knight.Bean.SchemaIndexStatistics;
import com.knight.Bean.SchemaIndexStatisticsExample;
import com.knight.Bean.SchemaIndexStatisticsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchemaIndexStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_index_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(SchemaIndexStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_index_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(SchemaIndexStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_index_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(SchemaIndexStatisticsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_index_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(SchemaIndexStatisticsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_index_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<SchemaIndexStatisticsWithBLOBs> selectByExampleWithBLOBs(SchemaIndexStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_index_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<SchemaIndexStatistics> selectByExample(SchemaIndexStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_index_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") SchemaIndexStatisticsWithBLOBs record, @Param("example") SchemaIndexStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_index_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SchemaIndexStatisticsWithBLOBs record, @Param("example") SchemaIndexStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema_index_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") SchemaIndexStatistics record, @Param("example") SchemaIndexStatisticsExample example);
}