package com.knight.Dao;

import com.knight.Bean.Securityuser;
import com.knight.Bean.SecurityuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecurityuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityuser
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SecurityuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityuser
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SecurityuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityuser
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(Securityuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityuser
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(Securityuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityuser
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Securityuser> selectByExample(SecurityuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityuser
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Securityuser record, @Param("example") SecurityuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityuser
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") Securityuser record, @Param("example") SecurityuserExample example);
}