package com.knight.Dao;

import com.knight.Bean.Servers;
import com.knight.Bean.ServersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(ServersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(ServersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(Servers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(Servers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Servers> selectByExample(ServersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Servers record, @Param("example") ServersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") Servers record, @Param("example") ServersExample example);
}