package com.knight.Dao;

import com.knight.Bean.ServerCost;
import com.knight.Bean.ServerCostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServerCostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_cost
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(ServerCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_cost
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(ServerCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_cost
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(ServerCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_cost
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(ServerCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_cost
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<ServerCost> selectByExample(ServerCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_cost
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") ServerCost record, @Param("example") ServerCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_cost
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") ServerCost record, @Param("example") ServerCostExample example);
}