package com.knight.Dao;

import com.knight.Bean.SessionConnectAttrs;
import com.knight.Bean.SessionConnectAttrsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SessionConnectAttrsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_connect_attrs
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SessionConnectAttrsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_connect_attrs
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SessionConnectAttrsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_connect_attrs
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SessionConnectAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_connect_attrs
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SessionConnectAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_connect_attrs
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SessionConnectAttrs> selectByExample(SessionConnectAttrsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_connect_attrs
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SessionConnectAttrs record, @Param("example") SessionConnectAttrsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_connect_attrs
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") SessionConnectAttrs record, @Param("example") SessionConnectAttrsExample example);
}