package com.knight.Dao;

import com.knight.Bean.SessionAccountConnectAttrs;
import com.knight.Bean.SessionAccountConnectAttrsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SessionAccountConnectAttrsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_account_connect_attrs
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SessionAccountConnectAttrsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_account_connect_attrs
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SessionAccountConnectAttrsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_account_connect_attrs
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SessionAccountConnectAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_account_connect_attrs
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SessionAccountConnectAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_account_connect_attrs
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SessionAccountConnectAttrs> selectByExample(SessionAccountConnectAttrsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_account_connect_attrs
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SessionAccountConnectAttrs record, @Param("example") SessionAccountConnectAttrsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session_account_connect_attrs
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") SessionAccountConnectAttrs record, @Param("example") SessionAccountConnectAttrsExample example);
}