package com.knight.Dao;

import com.knight.Bean.Session;
import com.knight.Bean.SessionExample;
import com.knight.Bean.SessionWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SessionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SessionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SessionWithBLOBs> selectByExampleWithBLOBs(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Session> selectByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SessionWithBLOBs record, @Param("example") SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SessionWithBLOBs record, @Param("example") SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table session
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") Session record, @Param("example") SessionExample example);
}