package com.knight.Dao;

import com.knight.Bean.SetupTimers;
import com.knight.Bean.SetupTimersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SetupTimersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_timers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SetupTimersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_timers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SetupTimersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_timers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SetupTimers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_timers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SetupTimers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_timers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SetupTimers> selectByExample(SetupTimersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_timers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SetupTimers record, @Param("example") SetupTimersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_timers
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") SetupTimers record, @Param("example") SetupTimersExample example);
}