package com.knight.Dao;

import com.knight.Bean.SetupConsumers;
import com.knight.Bean.SetupConsumersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SetupConsumersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_consumers
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(SetupConsumersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_consumers
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(SetupConsumersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_consumers
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(SetupConsumers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_consumers
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(SetupConsumers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_consumers
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<SetupConsumers> selectByExample(SetupConsumersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_consumers
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") SetupConsumers record, @Param("example") SetupConsumersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_consumers
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") SetupConsumers record, @Param("example") SetupConsumersExample example);
}