package com.knight.Dao;

import com.knight.Bean.SetupActors;
import com.knight.Bean.SetupActorsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SetupActorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_actors
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SetupActorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_actors
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SetupActorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_actors
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SetupActors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_actors
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SetupActors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_actors
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SetupActors> selectByExample(SetupActorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_actors
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SetupActors record, @Param("example") SetupActorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setup_actors
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") SetupActors record, @Param("example") SetupActorsExample example);
}