package com.knight.Dao;

import com.knight.Bean.sheetcomment;

public interface sheetcommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheetcomment
     *
     * @mbg.generated Sat Dec 28 12:48:10 CST 2019
     */
    int insert(sheetcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheetcomment
     *
     * @mbg.generated Sat Dec 28 12:48:10 CST 2019
     */
    int insertSelective(sheetcomment record);
}