package com.knight.Dao;

import com.knight.Bean.SheetCommentInfoV;
import com.knight.Bean.SheetCommentInfoVExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SheetCommentInfoVMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SheetCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SheetCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SheetCommentInfoV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SheetCommentInfoV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SheetCommentInfoV> selectByExampleWithBLOBs(SheetCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SheetCommentInfoV> selectByExample(SheetCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SheetCommentInfoV record, @Param("example") SheetCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SheetCommentInfoV record, @Param("example") SheetCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheet_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") SheetCommentInfoV record, @Param("example") SheetCommentInfoVExample example);
}