package com.knight.Dao;

import com.knight.Bean.singerbaseinfo;

public interface singerbaseinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 12:48:10 CST 2019
     */
    int insert(singerbaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 12:48:10 CST 2019
     */
    int insertSelective(singerbaseinfo record);
}