package com.knight.Dao;

import com.knight.Bean.SlaveRelayLogInfo;
import com.knight.Bean.SlaveRelayLogInfoExample;
import com.knight.Bean.SlaveRelayLogInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlaveRelayLogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SlaveRelayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SlaveRelayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SlaveRelayLogInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SlaveRelayLogInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SlaveRelayLogInfoWithBLOBs> selectByExampleWithBLOBs(SlaveRelayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SlaveRelayLogInfo> selectByExample(SlaveRelayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SlaveRelayLogInfoWithBLOBs record, @Param("example") SlaveRelayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SlaveRelayLogInfoWithBLOBs record, @Param("example") SlaveRelayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_relay_log_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") SlaveRelayLogInfo record, @Param("example") SlaveRelayLogInfoExample example);
}