package com.knight.Dao;

import com.knight.Bean.SlaveWorkerInfo;
import com.knight.Bean.SlaveWorkerInfoExample;
import com.knight.Bean.SlaveWorkerInfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlaveWorkerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SlaveWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SlaveWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SlaveWorkerInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SlaveWorkerInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SlaveWorkerInfoWithBLOBs> selectByExampleWithBLOBs(SlaveWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SlaveWorkerInfo> selectByExample(SlaveWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SlaveWorkerInfoWithBLOBs record, @Param("example") SlaveWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SlaveWorkerInfoWithBLOBs record, @Param("example") SlaveWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slave_worker_info
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") SlaveWorkerInfo record, @Param("example") SlaveWorkerInfoExample example);
}