package com.knight.Dao;

import com.knight.Bean.SocketSummaryByInstance;
import com.knight.Bean.SocketSummaryByInstanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SocketSummaryByInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_summary_by_instance
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SocketSummaryByInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_summary_by_instance
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SocketSummaryByInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_summary_by_instance
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SocketSummaryByInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_summary_by_instance
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SocketSummaryByInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_summary_by_instance
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SocketSummaryByInstance> selectByExample(SocketSummaryByInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_summary_by_instance
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SocketSummaryByInstance record, @Param("example") SocketSummaryByInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_summary_by_instance
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") SocketSummaryByInstance record, @Param("example") SocketSummaryByInstanceExample example);
}