package com.knight.Dao;

import com.knight.Bean.SocketInstances;
import com.knight.Bean.SocketInstancesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SocketInstancesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SocketInstancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SocketInstancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SocketInstances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SocketInstances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SocketInstances> selectByExample(SocketInstancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SocketInstances record, @Param("example") SocketInstancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_instances
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") SocketInstances record, @Param("example") SocketInstancesExample example);
}