package com.knight.Dao;

import com.knight.Bean.SongsheetV;
import com.knight.Bean.SongsheetVExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SongsheetVMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheet_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(SongsheetVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheet_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(SongsheetVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheet_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(SongsheetV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheet_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(SongsheetV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheet_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SongsheetV> selectByExampleWithBLOBs(SongsheetVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheet_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<SongsheetV> selectByExample(SongsheetVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheet_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") SongsheetV record, @Param("example") SongsheetVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheet_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SongsheetV record, @Param("example") SongsheetVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheet_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") SongsheetV record, @Param("example") SongsheetVExample example);
}