package com.knight.Dao;

import com.knight.Bean.songsheet;

public interface songsheetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheet
     *
     * @mbg.generated Sat Dec 28 12:48:10 CST 2019
     */
    int insert(songsheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheet
     *
     * @mbg.generated Sat Dec 28 12:48:10 CST 2019
     */
    int insertSelective(songsheet record);
}