package com.knight.Dao;

import com.knight.Bean.Statistics;
import com.knight.Bean.StatisticsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Statistics> selectByExample(StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Statistics record, @Param("example") StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") Statistics record, @Param("example") StatisticsExample example);
}