package com.knight.Dao;

import com.knight.Bean.StatementsWithRuntimesIn95thPercentile;
import com.knight.Bean.StatementsWithRuntimesIn95thPercentileExample;
import com.knight.Bean.StatementsWithRuntimesIn95thPercentileWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatementsWithRuntimesIn95thPercentileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(StatementsWithRuntimesIn95thPercentileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(StatementsWithRuntimesIn95thPercentileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(StatementsWithRuntimesIn95thPercentileWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(StatementsWithRuntimesIn95thPercentileWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<StatementsWithRuntimesIn95thPercentileWithBLOBs> selectByExampleWithBLOBs(StatementsWithRuntimesIn95thPercentileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<StatementsWithRuntimesIn95thPercentile> selectByExample(StatementsWithRuntimesIn95thPercentileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") StatementsWithRuntimesIn95thPercentileWithBLOBs record, @Param("example") StatementsWithRuntimesIn95thPercentileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") StatementsWithRuntimesIn95thPercentileWithBLOBs record, @Param("example") StatementsWithRuntimesIn95thPercentileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") StatementsWithRuntimesIn95thPercentile record, @Param("example") StatementsWithRuntimesIn95thPercentileExample example);
}