package com.knight.Dao;

import com.knight.Bean.StatementsWithFullTableScans;
import com.knight.Bean.StatementsWithFullTableScansExample;
import com.knight.Bean.StatementsWithFullTableScansWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatementsWithFullTableScansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(StatementsWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(StatementsWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(StatementsWithFullTableScansWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(StatementsWithFullTableScansWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<StatementsWithFullTableScansWithBLOBs> selectByExampleWithBLOBs(StatementsWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<StatementsWithFullTableScans> selectByExample(StatementsWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") StatementsWithFullTableScansWithBLOBs record, @Param("example") StatementsWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") StatementsWithFullTableScansWithBLOBs record, @Param("example") StatementsWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") StatementsWithFullTableScans record, @Param("example") StatementsWithFullTableScansExample example);
}