package com.knight.Dao;

import com.knight.Bean.StatementsWithTempTables;
import com.knight.Bean.StatementsWithTempTablesExample;
import com.knight.Bean.StatementsWithTempTablesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatementsWithTempTablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(StatementsWithTempTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(StatementsWithTempTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(StatementsWithTempTablesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(StatementsWithTempTablesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<StatementsWithTempTablesWithBLOBs> selectByExampleWithBLOBs(StatementsWithTempTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<StatementsWithTempTables> selectByExample(StatementsWithTempTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") StatementsWithTempTablesWithBLOBs record, @Param("example") StatementsWithTempTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") StatementsWithTempTablesWithBLOBs record, @Param("example") StatementsWithTempTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") StatementsWithTempTables record, @Param("example") StatementsWithTempTablesExample example);
}