package com.knight.Dao;

import com.knight.Bean.StatementAnalysis;
import com.knight.Bean.StatementAnalysisExample;
import com.knight.Bean.StatementAnalysisWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatementAnalysisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(StatementAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(StatementAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(StatementAnalysisWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(StatementAnalysisWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<StatementAnalysisWithBLOBs> selectByExampleWithBLOBs(StatementAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<StatementAnalysis> selectByExample(StatementAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") StatementAnalysisWithBLOBs record, @Param("example") StatementAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") StatementAnalysisWithBLOBs record, @Param("example") StatementAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") StatementAnalysis record, @Param("example") StatementAnalysisExample example);
}