package com.knight.Dao;

import com.knight.Bean.StatementsWithSorting;
import com.knight.Bean.StatementsWithSortingExample;
import com.knight.Bean.StatementsWithSortingWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatementsWithSortingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_sorting
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(StatementsWithSortingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_sorting
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(StatementsWithSortingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_sorting
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(StatementsWithSortingWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_sorting
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(StatementsWithSortingWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_sorting
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<StatementsWithSortingWithBLOBs> selectByExampleWithBLOBs(StatementsWithSortingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_sorting
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<StatementsWithSorting> selectByExample(StatementsWithSortingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_sorting
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") StatementsWithSortingWithBLOBs record, @Param("example") StatementsWithSortingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_sorting
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") StatementsWithSortingWithBLOBs record, @Param("example") StatementsWithSortingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statements_with_sorting
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") StatementsWithSorting record, @Param("example") StatementsWithSortingExample example);
}