package com.knight.Dao;

import com.knight.Bean.Tablespaces;
import com.knight.Bean.TablespacesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TablespacesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLESPACES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(TablespacesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLESPACES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(TablespacesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLESPACES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(Tablespaces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLESPACES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(Tablespaces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLESPACES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Tablespaces> selectByExample(TablespacesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLESPACES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tablespaces record, @Param("example") TablespacesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLESPACES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") Tablespaces record, @Param("example") TablespacesExample example);
}