package com.knight.Dao;

import com.knight.Bean.TablesPriv;
import com.knight.Bean.TablesPrivExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TablesPrivMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(TablesPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(TablesPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(TablesPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(TablesPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<TablesPriv> selectByExample(TablesPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") TablesPriv record, @Param("example") TablesPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tables_priv
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") TablesPriv record, @Param("example") TablesPrivExample example);
}