package com.knight.Dao;

import com.knight.Bean.TableLockWaitsSummaryByTable;
import com.knight.Bean.TableLockWaitsSummaryByTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableLockWaitsSummaryByTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_lock_waits_summary_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(TableLockWaitsSummaryByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_lock_waits_summary_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(TableLockWaitsSummaryByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_lock_waits_summary_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(TableLockWaitsSummaryByTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_lock_waits_summary_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(TableLockWaitsSummaryByTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_lock_waits_summary_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<TableLockWaitsSummaryByTable> selectByExample(TableLockWaitsSummaryByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_lock_waits_summary_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") TableLockWaitsSummaryByTable record, @Param("example") TableLockWaitsSummaryByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_lock_waits_summary_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") TableLockWaitsSummaryByTable record, @Param("example") TableLockWaitsSummaryByTableExample example);
}