package com.knight.Dao;

import com.knight.Bean.Threads;
import com.knight.Bean.ThreadsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThreadsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threads
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(ThreadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threads
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(ThreadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threads
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(Threads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threads
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(Threads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threads
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<Threads> selectByExampleWithBLOBs(ThreadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threads
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<Threads> selectByExample(ThreadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threads
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") Threads record, @Param("example") ThreadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threads
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Threads record, @Param("example") ThreadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threads
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") Threads record, @Param("example") ThreadsExample example);
}