package com.knight.Dao;

import com.knight.Bean.TimeZoneTransitionType;
import com.knight.Bean.TimeZoneTransitionTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeZoneTransitionTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(TimeZoneTransitionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(TimeZoneTransitionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(TimeZoneTransitionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(TimeZoneTransitionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<TimeZoneTransitionType> selectByExample(TimeZoneTransitionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") TimeZoneTransitionType record, @Param("example") TimeZoneTransitionTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_zone_transition_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") TimeZoneTransitionType record, @Param("example") TimeZoneTransitionTypeExample example);
}