package com.knight.Dao;

import com.knight.Bean.TrackCommentInfoV;
import com.knight.Bean.TrackCommentInfoVExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrackCommentInfoVMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(TrackCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(TrackCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(TrackCommentInfoV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(TrackCommentInfoV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<TrackCommentInfoV> selectByExampleWithBLOBs(TrackCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<TrackCommentInfoV> selectByExample(TrackCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") TrackCommentInfoV record, @Param("example") TrackCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") TrackCommentInfoV record, @Param("example") TrackCommentInfoVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track_comment_info_v
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") TrackCommentInfoV record, @Param("example") TrackCommentInfoVExample example);
}