package com.knight.Dao;

import com.knight.Bean.UserSummaryByStages;
import com.knight.Bean.UserSummaryByStagesExample;
import com.knight.Bean.UserSummaryByStagesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSummaryByStagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(UserSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(UserSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(UserSummaryByStagesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(UserSummaryByStagesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<UserSummaryByStagesWithBLOBs> selectByExampleWithBLOBs(UserSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<UserSummaryByStages> selectByExample(UserSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserSummaryByStagesWithBLOBs record, @Param("example") UserSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") UserSummaryByStagesWithBLOBs record, @Param("example") UserSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") UserSummaryByStages record, @Param("example") UserSummaryByStagesExample example);
}