package com.knight.Dao;

import com.knight.Bean.usercollectioninfo;

public interface usercollectioninfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollectioninfo
     *
     * @mbg.generated Sat Dec 28 12:48:10 CST 2019
     */
    int insert(usercollectioninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollectioninfo
     *
     * @mbg.generated Sat Dec 28 12:48:10 CST 2019
     */
    int insertSelective(usercollectioninfo record);
}