package com.knight.Dao;

import com.knight.Bean.UsercollectionV;
import com.knight.Bean.UsercollectionVExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsercollectionVMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollection_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(UsercollectionVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollection_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(UsercollectionVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollection_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(UsercollectionV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollection_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(UsercollectionV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollection_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<UsercollectionV> selectByExampleWithBLOBs(UsercollectionVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollection_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<UsercollectionV> selectByExample(UsercollectionVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollection_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") UsercollectionV record, @Param("example") UsercollectionVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollection_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") UsercollectionV record, @Param("example") UsercollectionVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollection_v
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") UsercollectionV record, @Param("example") UsercollectionVExample example);
}