package com.knight.Dao;

import com.knight.Bean.UserSummaryByStatementType;
import com.knight.Bean.UserSummaryByStatementTypeExample;
import com.knight.Bean.UserSummaryByStatementTypeWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSummaryByStatementTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(UserSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(UserSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(UserSummaryByStatementTypeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(UserSummaryByStatementTypeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<UserSummaryByStatementTypeWithBLOBs> selectByExampleWithBLOBs(UserSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<UserSummaryByStatementType> selectByExample(UserSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserSummaryByStatementTypeWithBLOBs record, @Param("example") UserSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") UserSummaryByStatementTypeWithBLOBs record, @Param("example") UserSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") UserSummaryByStatementType record, @Param("example") UserSummaryByStatementTypeExample example);
}