package com.knight.Dao;

import com.knight.Bean.UserPrivileges;
import com.knight.Bean.UserPrivilegesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPrivilegesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PRIVILEGES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(UserPrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PRIVILEGES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(UserPrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PRIVILEGES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(UserPrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PRIVILEGES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(UserPrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PRIVILEGES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<UserPrivileges> selectByExample(UserPrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PRIVILEGES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserPrivileges record, @Param("example") UserPrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PRIVILEGES
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") UserPrivileges record, @Param("example") UserPrivilegesExample example);
}