package com.knight.Dao;

import com.knight.Bean.UserSummaryByFileIo;
import com.knight.Bean.UserSummaryByFileIoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSummaryByFileIoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(UserSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(UserSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(UserSummaryByFileIo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(UserSummaryByFileIo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<UserSummaryByFileIo> selectByExampleWithBLOBs(UserSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<UserSummaryByFileIo> selectByExample(UserSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserSummaryByFileIo record, @Param("example") UserSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") UserSummaryByFileIo record, @Param("example") UserSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") UserSummaryByFileIo record, @Param("example") UserSummaryByFileIoExample example);
}