package com.knight.Dao;

import com.knight.Bean.UserSummaryByFileIoType;
import com.knight.Bean.UserSummaryByFileIoTypeExample;
import com.knight.Bean.UserSummaryByFileIoTypeWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSummaryByFileIoTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(UserSummaryByFileIoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(UserSummaryByFileIoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(UserSummaryByFileIoTypeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(UserSummaryByFileIoTypeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<UserSummaryByFileIoTypeWithBLOBs> selectByExampleWithBLOBs(UserSummaryByFileIoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<UserSummaryByFileIoType> selectByExample(UserSummaryByFileIoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserSummaryByFileIoTypeWithBLOBs record, @Param("example") UserSummaryByFileIoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") UserSummaryByFileIoTypeWithBLOBs record, @Param("example") UserSummaryByFileIoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") UserSummaryByFileIoType record, @Param("example") UserSummaryByFileIoTypeExample example);
}