package com.knight.Dao;

import com.knight.Bean.Views;
import com.knight.Bean.ViewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ViewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(ViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(ViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(Views record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(Views record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Views> selectByExampleWithBLOBs(ViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<Views> selectByExample(ViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Views record, @Param("example") ViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Views record, @Param("example") ViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIEWS
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") Views record, @Param("example") ViewsExample example);
}