package com.knight.Dao;

import com.knight.Bean.WaitsGlobalByLatency;
import com.knight.Bean.WaitsGlobalByLatencyExample;
import com.knight.Bean.WaitsGlobalByLatencyWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WaitsGlobalByLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(WaitsGlobalByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(WaitsGlobalByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(WaitsGlobalByLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(WaitsGlobalByLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<WaitsGlobalByLatencyWithBLOBs> selectByExampleWithBLOBs(WaitsGlobalByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<WaitsGlobalByLatency> selectByExample(WaitsGlobalByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") WaitsGlobalByLatencyWithBLOBs record, @Param("example") WaitsGlobalByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") WaitsGlobalByLatencyWithBLOBs record, @Param("example") WaitsGlobalByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") WaitsGlobalByLatency record, @Param("example") WaitsGlobalByLatencyExample example);
}