package com.knight.Dao;

import com.knight.Bean.WaitClassesGlobalByAvgLatency;
import com.knight.Bean.WaitClassesGlobalByAvgLatencyExample;
import com.knight.Bean.WaitClassesGlobalByAvgLatencyWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WaitClassesGlobalByAvgLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_avg_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(WaitClassesGlobalByAvgLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_avg_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(WaitClassesGlobalByAvgLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_avg_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(WaitClassesGlobalByAvgLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_avg_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(WaitClassesGlobalByAvgLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_avg_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<WaitClassesGlobalByAvgLatencyWithBLOBs> selectByExampleWithBLOBs(WaitClassesGlobalByAvgLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_avg_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<WaitClassesGlobalByAvgLatency> selectByExample(WaitClassesGlobalByAvgLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_avg_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") WaitClassesGlobalByAvgLatencyWithBLOBs record, @Param("example") WaitClassesGlobalByAvgLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_avg_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") WaitClassesGlobalByAvgLatencyWithBLOBs record, @Param("example") WaitClassesGlobalByAvgLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_avg_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") WaitClassesGlobalByAvgLatency record, @Param("example") WaitClassesGlobalByAvgLatencyExample example);
}