package com.knight.Dao;

import com.knight.Bean.WaitsByHostByLatency;
import com.knight.Bean.WaitsByHostByLatencyExample;
import com.knight.Bean.WaitsByHostByLatencyWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WaitsByHostByLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_by_host_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(WaitsByHostByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_by_host_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(WaitsByHostByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_by_host_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(WaitsByHostByLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_by_host_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(WaitsByHostByLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_by_host_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<WaitsByHostByLatencyWithBLOBs> selectByExampleWithBLOBs(WaitsByHostByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_by_host_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<WaitsByHostByLatency> selectByExample(WaitsByHostByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_by_host_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") WaitsByHostByLatencyWithBLOBs record, @Param("example") WaitsByHostByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_by_host_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") WaitsByHostByLatencyWithBLOBs record, @Param("example") WaitsByHostByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waits_by_host_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") WaitsByHostByLatency record, @Param("example") WaitsByHostByLatencyExample example);
}