package com.knight.Dao;

import com.knight.Bean.WaitClassesGlobalByLatency;
import com.knight.Bean.WaitClassesGlobalByLatencyExample;
import com.knight.Bean.WaitClassesGlobalByLatencyWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WaitClassesGlobalByLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(WaitClassesGlobalByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(WaitClassesGlobalByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(WaitClassesGlobalByLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(WaitClassesGlobalByLatencyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<WaitClassesGlobalByLatencyWithBLOBs> selectByExampleWithBLOBs(WaitClassesGlobalByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<WaitClassesGlobalByLatency> selectByExample(WaitClassesGlobalByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") WaitClassesGlobalByLatencyWithBLOBs record, @Param("example") WaitClassesGlobalByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") WaitClassesGlobalByLatencyWithBLOBs record, @Param("example") WaitClassesGlobalByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_classes_global_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") WaitClassesGlobalByLatency record, @Param("example") WaitClassesGlobalByLatencyExample example);
}