package com.knight.Dao;

import com.knight.Bean.XHostSummaryByFileIo;
import com.knight.Bean.XHostSummaryByFileIoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XHostSummaryByFileIoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XHostSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XHostSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XHostSummaryByFileIo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XHostSummaryByFileIo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XHostSummaryByFileIo> selectByExample(XHostSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XHostSummaryByFileIo record, @Param("example") XHostSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XHostSummaryByFileIo record, @Param("example") XHostSummaryByFileIoExample example);
}