package com.knight.Dao;

import com.knight.Bean.XHostSummaryByStatementLatency;
import com.knight.Bean.XHostSummaryByStatementLatencyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XHostSummaryByStatementLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XHostSummaryByStatementLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XHostSummaryByStatementLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XHostSummaryByStatementLatency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XHostSummaryByStatementLatency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XHostSummaryByStatementLatency> selectByExample(XHostSummaryByStatementLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XHostSummaryByStatementLatency record, @Param("example") XHostSummaryByStatementLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_statement_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XHostSummaryByStatementLatency record, @Param("example") XHostSummaryByStatementLatencyExample example);
}