package com.knight.Dao;

import com.knight.Bean.XHostSummaryByFileIoType;
import com.knight.Bean.XHostSummaryByFileIoTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XHostSummaryByFileIoTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XHostSummaryByFileIoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XHostSummaryByFileIoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XHostSummaryByFileIoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XHostSummaryByFileIoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XHostSummaryByFileIoType> selectByExample(XHostSummaryByFileIoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XHostSummaryByFileIoType record, @Param("example") XHostSummaryByFileIoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_file_io_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XHostSummaryByFileIoType record, @Param("example") XHostSummaryByFileIoTypeExample example);
}