package com.knight.Dao;

import com.knight.Bean.XHostSummaryByStages;
import com.knight.Bean.XHostSummaryByStagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XHostSummaryByStagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XHostSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XHostSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XHostSummaryByStages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XHostSummaryByStages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XHostSummaryByStages> selectByExample(XHostSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XHostSummaryByStages record, @Param("example") XHostSummaryByStagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$host_summary_by_stages
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XHostSummaryByStages record, @Param("example") XHostSummaryByStagesExample example);
}