package com.knight.Dao;

import com.knight.Bean.XInnodbBufferStatsBySchema;
import com.knight.Bean.XInnodbBufferStatsBySchemaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XInnodbBufferStatsBySchemaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XInnodbBufferStatsBySchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XInnodbBufferStatsBySchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XInnodbBufferStatsBySchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XInnodbBufferStatsBySchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XInnodbBufferStatsBySchema> selectByExampleWithBLOBs(XInnodbBufferStatsBySchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XInnodbBufferStatsBySchema> selectByExample(XInnodbBufferStatsBySchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XInnodbBufferStatsBySchema record, @Param("example") XInnodbBufferStatsBySchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") XInnodbBufferStatsBySchema record, @Param("example") XInnodbBufferStatsBySchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_schema
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XInnodbBufferStatsBySchema record, @Param("example") XInnodbBufferStatsBySchemaExample example);
}