package com.knight.Dao;

import com.knight.Bean.XInnodbBufferStatsByTable;
import com.knight.Bean.XInnodbBufferStatsByTableExample;
import com.knight.Bean.XInnodbBufferStatsByTableWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XInnodbBufferStatsByTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XInnodbBufferStatsByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XInnodbBufferStatsByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XInnodbBufferStatsByTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XInnodbBufferStatsByTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XInnodbBufferStatsByTableWithBLOBs> selectByExampleWithBLOBs(XInnodbBufferStatsByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XInnodbBufferStatsByTable> selectByExample(XInnodbBufferStatsByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XInnodbBufferStatsByTableWithBLOBs record, @Param("example") XInnodbBufferStatsByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") XInnodbBufferStatsByTableWithBLOBs record, @Param("example") XInnodbBufferStatsByTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_buffer_stats_by_table
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XInnodbBufferStatsByTable record, @Param("example") XInnodbBufferStatsByTableExample example);
}