package com.knight.Dao;

import com.knight.Bean.XInnodbLockWaits;
import com.knight.Bean.XInnodbLockWaitsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XInnodbLockWaitsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XInnodbLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XInnodbLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XInnodbLockWaits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XInnodbLockWaits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XInnodbLockWaits> selectByExample(XInnodbLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XInnodbLockWaits record, @Param("example") XInnodbLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$innodb_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XInnodbLockWaits record, @Param("example") XInnodbLockWaitsExample example);
}