package com.knight.Dao;

import com.knight.Bean.XIoGlobalByFileByBytes;
import com.knight.Bean.XIoGlobalByFileByBytesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XIoGlobalByFileByBytesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_file_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XIoGlobalByFileByBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_file_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XIoGlobalByFileByBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_file_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XIoGlobalByFileByBytes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_file_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XIoGlobalByFileByBytes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_file_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XIoGlobalByFileByBytes> selectByExample(XIoGlobalByFileByBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_file_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XIoGlobalByFileByBytes record, @Param("example") XIoGlobalByFileByBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_file_by_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XIoGlobalByFileByBytes record, @Param("example") XIoGlobalByFileByBytesExample example);
}