package com.knight.Dao;

import com.knight.Bean.XIoGlobalByFileByLatency;
import com.knight.Bean.XIoGlobalByFileByLatencyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XIoGlobalByFileByLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XIoGlobalByFileByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XIoGlobalByFileByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XIoGlobalByFileByLatency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XIoGlobalByFileByLatency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XIoGlobalByFileByLatency> selectByExample(XIoGlobalByFileByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XIoGlobalByFileByLatency record, @Param("example") XIoGlobalByFileByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$io_global_by_file_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XIoGlobalByFileByLatency record, @Param("example") XIoGlobalByFileByLatencyExample example);
}