package com.knight.Dao;

import com.knight.Bean.XMemoryByHostByCurrentBytes;
import com.knight.Bean.XMemoryByHostByCurrentBytesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XMemoryByHostByCurrentBytesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XMemoryByHostByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XMemoryByHostByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XMemoryByHostByCurrentBytes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XMemoryByHostByCurrentBytes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XMemoryByHostByCurrentBytes> selectByExample(XMemoryByHostByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XMemoryByHostByCurrentBytes record, @Param("example") XMemoryByHostByCurrentBytesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$memory_by_host_by_current_bytes
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XMemoryByHostByCurrentBytes record, @Param("example") XMemoryByHostByCurrentBytesExample example);
}