package com.knight.Dao;

import com.knight.Bean.XProcesslist;
import com.knight.Bean.XProcesslistExample;
import com.knight.Bean.XProcesslistWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XProcesslistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$processlist
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XProcesslistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$processlist
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XProcesslistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$processlist
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XProcesslistWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$processlist
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XProcesslistWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$processlist
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XProcesslistWithBLOBs> selectByExampleWithBLOBs(XProcesslistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$processlist
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XProcesslist> selectByExample(XProcesslistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$processlist
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XProcesslistWithBLOBs record, @Param("example") XProcesslistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$processlist
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") XProcesslistWithBLOBs record, @Param("example") XProcesslistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$processlist
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XProcesslist record, @Param("example") XProcesslistExample example);
}