package com.knight.Dao;

import com.knight.Bean.XPsDigestAvgLatencyDistribution;
import com.knight.Bean.XPsDigestAvgLatencyDistributionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XPsDigestAvgLatencyDistributionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$ps_digest_avg_latency_distribution
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XPsDigestAvgLatencyDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$ps_digest_avg_latency_distribution
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XPsDigestAvgLatencyDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$ps_digest_avg_latency_distribution
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XPsDigestAvgLatencyDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$ps_digest_avg_latency_distribution
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XPsDigestAvgLatencyDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$ps_digest_avg_latency_distribution
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XPsDigestAvgLatencyDistribution> selectByExample(XPsDigestAvgLatencyDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$ps_digest_avg_latency_distribution
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XPsDigestAvgLatencyDistribution record, @Param("example") XPsDigestAvgLatencyDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$ps_digest_avg_latency_distribution
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XPsDigestAvgLatencyDistribution record, @Param("example") XPsDigestAvgLatencyDistributionExample example);
}