package com.knight.Dao;

import com.knight.Bean.XPsSchemaTableStatisticsIo;
import com.knight.Bean.XPsSchemaTableStatisticsIoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XPsSchemaTableStatisticsIoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$ps_schema_table_statistics_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XPsSchemaTableStatisticsIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$ps_schema_table_statistics_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XPsSchemaTableStatisticsIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$ps_schema_table_statistics_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XPsSchemaTableStatisticsIo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$ps_schema_table_statistics_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XPsSchemaTableStatisticsIo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$ps_schema_table_statistics_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XPsSchemaTableStatisticsIo> selectByExample(XPsSchemaTableStatisticsIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$ps_schema_table_statistics_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XPsSchemaTableStatisticsIo record, @Param("example") XPsSchemaTableStatisticsIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$ps_schema_table_statistics_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XPsSchemaTableStatisticsIo record, @Param("example") XPsSchemaTableStatisticsIoExample example);
}