package com.knight.Dao;

import com.knight.Bean.XSchemaTableLockWaits;
import com.knight.Bean.XSchemaTableLockWaitsExample;
import com.knight.Bean.XSchemaTableLockWaitsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XSchemaTableLockWaitsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XSchemaTableLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XSchemaTableLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XSchemaTableLockWaitsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XSchemaTableLockWaitsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XSchemaTableLockWaitsWithBLOBs> selectByExampleWithBLOBs(XSchemaTableLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XSchemaTableLockWaits> selectByExample(XSchemaTableLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XSchemaTableLockWaitsWithBLOBs record, @Param("example") XSchemaTableLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") XSchemaTableLockWaitsWithBLOBs record, @Param("example") XSchemaTableLockWaitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_lock_waits
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XSchemaTableLockWaits record, @Param("example") XSchemaTableLockWaitsExample example);
}