package com.knight.Dao;

import com.knight.Bean.XSchemaTableStatisticsWithBuffer;
import com.knight.Bean.XSchemaTableStatisticsWithBufferExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XSchemaTableStatisticsWithBufferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_statistics_with_buffer
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XSchemaTableStatisticsWithBufferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_statistics_with_buffer
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XSchemaTableStatisticsWithBufferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_statistics_with_buffer
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XSchemaTableStatisticsWithBuffer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_statistics_with_buffer
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XSchemaTableStatisticsWithBuffer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_statistics_with_buffer
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XSchemaTableStatisticsWithBuffer> selectByExample(XSchemaTableStatisticsWithBufferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_statistics_with_buffer
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XSchemaTableStatisticsWithBuffer record, @Param("example") XSchemaTableStatisticsWithBufferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_statistics_with_buffer
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XSchemaTableStatisticsWithBuffer record, @Param("example") XSchemaTableStatisticsWithBufferExample example);
}