package com.knight.Dao;

import com.knight.Bean.XSchemaTablesWithFullTableScans;
import com.knight.Bean.XSchemaTablesWithFullTableScansExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XSchemaTablesWithFullTableScansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XSchemaTablesWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XSchemaTablesWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XSchemaTablesWithFullTableScans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XSchemaTablesWithFullTableScans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XSchemaTablesWithFullTableScans> selectByExample(XSchemaTablesWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XSchemaTablesWithFullTableScans record, @Param("example") XSchemaTablesWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_tables_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XSchemaTablesWithFullTableScans record, @Param("example") XSchemaTablesWithFullTableScansExample example);
}