package com.knight.Dao;

import com.knight.Bean.XSchemaTableStatistics;
import com.knight.Bean.XSchemaTableStatisticsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XSchemaTableStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XSchemaTableStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XSchemaTableStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XSchemaTableStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XSchemaTableStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XSchemaTableStatistics> selectByExample(XSchemaTableStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XSchemaTableStatistics record, @Param("example") XSchemaTableStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$schema_table_statistics
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XSchemaTableStatistics record, @Param("example") XSchemaTableStatisticsExample example);
}