package com.knight.Dao;

import com.knight.Bean.XSession;
import com.knight.Bean.XSessionExample;
import com.knight.Bean.XSessionWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$session
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(XSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$session
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(XSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$session
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(XSessionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$session
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(XSessionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$session
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<XSessionWithBLOBs> selectByExampleWithBLOBs(XSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$session
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<XSession> selectByExample(XSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$session
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") XSessionWithBLOBs record, @Param("example") XSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$session
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") XSessionWithBLOBs record, @Param("example") XSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$session
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") XSession record, @Param("example") XSessionExample example);
}