package com.knight.Dao;

import com.knight.Bean.XStatementsWithRuntimesIn95thPercentile;
import com.knight.Bean.XStatementsWithRuntimesIn95thPercentileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XStatementsWithRuntimesIn95thPercentileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XStatementsWithRuntimesIn95thPercentileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XStatementsWithRuntimesIn95thPercentileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XStatementsWithRuntimesIn95thPercentile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XStatementsWithRuntimesIn95thPercentile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XStatementsWithRuntimesIn95thPercentile> selectByExampleWithBLOBs(XStatementsWithRuntimesIn95thPercentileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XStatementsWithRuntimesIn95thPercentile> selectByExample(XStatementsWithRuntimesIn95thPercentileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XStatementsWithRuntimesIn95thPercentile record, @Param("example") XStatementsWithRuntimesIn95thPercentileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") XStatementsWithRuntimesIn95thPercentile record, @Param("example") XStatementsWithRuntimesIn95thPercentileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_runtimes_in_95th_percentile
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XStatementsWithRuntimesIn95thPercentile record, @Param("example") XStatementsWithRuntimesIn95thPercentileExample example);
}