package com.knight.Dao;

import com.knight.Bean.XStatementsWithTempTables;
import com.knight.Bean.XStatementsWithTempTablesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XStatementsWithTempTablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XStatementsWithTempTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XStatementsWithTempTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XStatementsWithTempTables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XStatementsWithTempTables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XStatementsWithTempTables> selectByExampleWithBLOBs(XStatementsWithTempTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XStatementsWithTempTables> selectByExample(XStatementsWithTempTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XStatementsWithTempTables record, @Param("example") XStatementsWithTempTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") XStatementsWithTempTables record, @Param("example") XStatementsWithTempTablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_temp_tables
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XStatementsWithTempTables record, @Param("example") XStatementsWithTempTablesExample example);
}