package com.knight.Dao;

import com.knight.Bean.XStatementsWithErrorsOrWarnings;
import com.knight.Bean.XStatementsWithErrorsOrWarningsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XStatementsWithErrorsOrWarningsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_errors_or_warnings
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    long countByExample(XStatementsWithErrorsOrWarningsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_errors_or_warnings
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int deleteByExample(XStatementsWithErrorsOrWarningsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_errors_or_warnings
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insert(XStatementsWithErrorsOrWarnings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_errors_or_warnings
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int insertSelective(XStatementsWithErrorsOrWarnings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_errors_or_warnings
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<XStatementsWithErrorsOrWarnings> selectByExampleWithBLOBs(XStatementsWithErrorsOrWarningsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_errors_or_warnings
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    List<XStatementsWithErrorsOrWarnings> selectByExample(XStatementsWithErrorsOrWarningsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_errors_or_warnings
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") XStatementsWithErrorsOrWarnings record, @Param("example") XStatementsWithErrorsOrWarningsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_errors_or_warnings
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") XStatementsWithErrorsOrWarnings record, @Param("example") XStatementsWithErrorsOrWarningsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_errors_or_warnings
     *
     * @mbg.generated Sat Dec 28 12:31:55 CST 2019
     */
    int updateByExample(@Param("record") XStatementsWithErrorsOrWarnings record, @Param("example") XStatementsWithErrorsOrWarningsExample example);
}