package com.knight.Dao;

import com.knight.Bean.XStatementAnalysis;
import com.knight.Bean.XStatementAnalysisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XStatementAnalysisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XStatementAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XStatementAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XStatementAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XStatementAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XStatementAnalysis> selectByExampleWithBLOBs(XStatementAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XStatementAnalysis> selectByExample(XStatementAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XStatementAnalysis record, @Param("example") XStatementAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") XStatementAnalysis record, @Param("example") XStatementAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statement_analysis
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XStatementAnalysis record, @Param("example") XStatementAnalysisExample example);
}