package com.knight.Dao;

import com.knight.Bean.XStatementsWithFullTableScans;
import com.knight.Bean.XStatementsWithFullTableScansExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XStatementsWithFullTableScansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XStatementsWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XStatementsWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XStatementsWithFullTableScans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XStatementsWithFullTableScans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XStatementsWithFullTableScans> selectByExampleWithBLOBs(XStatementsWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XStatementsWithFullTableScans> selectByExample(XStatementsWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XStatementsWithFullTableScans record, @Param("example") XStatementsWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") XStatementsWithFullTableScans record, @Param("example") XStatementsWithFullTableScansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$statements_with_full_table_scans
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XStatementsWithFullTableScans record, @Param("example") XStatementsWithFullTableScansExample example);
}