package com.knight.Dao;

import com.knight.Bean.XUserSummaryByStatementType;
import com.knight.Bean.XUserSummaryByStatementTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XUserSummaryByStatementTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XUserSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XUserSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XUserSummaryByStatementType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XUserSummaryByStatementType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XUserSummaryByStatementType> selectByExample(XUserSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XUserSummaryByStatementType record, @Param("example") XUserSummaryByStatementTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_statement_type
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XUserSummaryByStatementType record, @Param("example") XUserSummaryByStatementTypeExample example);
}