package com.knight.Dao;

import com.knight.Bean.XUserSummaryByFileIo;
import com.knight.Bean.XUserSummaryByFileIoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XUserSummaryByFileIoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XUserSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XUserSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XUserSummaryByFileIo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XUserSummaryByFileIo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XUserSummaryByFileIo> selectByExample(XUserSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XUserSummaryByFileIo record, @Param("example") XUserSummaryByFileIoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$user_summary_by_file_io
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XUserSummaryByFileIo record, @Param("example") XUserSummaryByFileIoExample example);
}