package com.knight.Dao;

import com.knight.Bean.XWaitsByUserByLatency;
import com.knight.Bean.XWaitsByUserByLatencyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XWaitsByUserByLatencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$waits_by_user_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    long countByExample(XWaitsByUserByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$waits_by_user_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int deleteByExample(XWaitsByUserByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$waits_by_user_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insert(XWaitsByUserByLatency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$waits_by_user_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int insertSelective(XWaitsByUserByLatency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$waits_by_user_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    List<XWaitsByUserByLatency> selectByExample(XWaitsByUserByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$waits_by_user_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") XWaitsByUserByLatency record, @Param("example") XWaitsByUserByLatencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$waits_by_user_by_latency
     *
     * @mbg.generated Sat Dec 28 12:31:56 CST 2019
     */
    int updateByExample(@Param("record") XWaitsByUserByLatency record, @Param("example") XWaitsByUserByLatencyExample example);
}