
package com.forget.cxf.webservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.forget.cxf.webservice.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://webservice.cxf.forget.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfo", targetNamespace = "http://webservice.cxf.forget.com/", className = "com.forget.cxf.webservice.GetInfo")
    @ResponseWrapper(localName = "getInfoResponse", targetNamespace = "http://webservice.cxf.forget.com/", className = "com.forget.cxf.webservice.GetInfoResponse")
    public String getInfo(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
