server:
  port: 8019

spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      username: root
#      password: root
      database: nightChat
      authentication-database: admin
      uri: mongodb://root:root@127.0.0.1:27017


